CREATE TABLE IF NOT EXISTS orgs (
  id VARCHAR(36) PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  title TEXT     NOT NULL UNIQUE,
  
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);